pool:
  vmImage: 'ubuntu-latest'
  
variables:
- group: 'AWS_TERRAFORM_PIPELINE'
- name: workingDirectory
  value: 'terraform/aws'
- name: bucketName
  value: 's3-eoghank-mgmt-terraform-aws-test-pipeline'

stages:
- stage: Plan
  jobs:
  - job: TerraformDeploy
    displayName: 'Deploy Terraform Resources'
    steps:

    - script: |
        terraform init -input=false
      displayName: 'Terraform Init'
      workingDirectory: $(workingDirectory)
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

    - script: |
        terraform plan -out=tfplan -var "bucket_name=$(bucketName)"
      displayName: 'Terraform Plan'
      workingDirectory: $(workingDirectory)
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(workingDirectory)/tfplan'
        artifactName: 'tfplan'
        publishLocation: 'pipeline'

- stage: Apply
  dependsOn: Plan
  jobs:
  - job: TerraformApply
    displayName: 'Terraform Apply'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: 'tfplan'
        targetPath: '$(workingDirectory)'
    
    - script: |
        terraform init -input=false
      displayName: 'Terraform Init'
      workingDirectory: $(workingDirectory)
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

    - script: |
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Apply'
      workingDirectory: $(workingDirectory)
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)